package shit.randomfoodstuff.render.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

public class ModelFatInfuser extends ModelBase {

    ModelRenderer BasePlate;
    ModelRenderer Pipe1;
    ModelRenderer Pipe2;
    ModelRenderer Pipe3;
    ModelRenderer Pipe4;
    ModelRenderer Lava1;
    ModelRenderer LavaTexture;
    ModelRenderer Lava2;
    ModelRenderer Lava3;
    ModelRenderer Lava4;
    ModelRenderer Lava5;
    ModelRenderer Lava6;
    ModelRenderer Lava7;
    ModelRenderer Lava8;
    ModelRenderer Lava9;
    ModelRenderer Fat1;
    ModelRenderer Fat2;
    ModelRenderer Fat3;
    ModelRenderer Fat4;
    ModelRenderer Fat5;
    ModelRenderer Fat6;
    ModelRenderer Pipe5;
    ModelRenderer Pipe6;

    public ModelFatInfuser() {
        textureWidth = 64;
        textureHeight = 128;

        BasePlate = new ModelRenderer(this, 0, 111);
        BasePlate.addBox(0F, 0F, 0F, 16, 1, 16);
        BasePlate.setRotationPoint(-8F, 23F, -8F);
        BasePlate.setTextureSize(64, 128);
        BasePlate.mirror = true;
        setRotation(BasePlate, 0F, 0F, 0F);
        Pipe1 = new ModelRenderer(this, 44, 0);
        Pipe1.addBox(0F, 0F, 0F, 5, 4, 5);
        Pipe1.setRotationPoint(-2F, 19F, 2F);
        Pipe1.setTextureSize(64, 128);
        Pipe1.mirror = true;
        setRotation(Pipe1, 0F, 0F, 0F);
        Pipe2 = new ModelRenderer(this, 56, 9);
        Pipe2.addBox(0F, 0F, 0F, 3, 1, 1);
        Pipe2.setRotationPoint(-2F, 16F, 4F);
        Pipe2.setTextureSize(64, 128);
        Pipe2.mirror = true;
        setRotation(Pipe2, 0F, 0F, 0.8922867F);
        Pipe3 = new ModelRenderer(this, 48, 9);
        Pipe3.addBox(0F, 0F, 0F, 2, 1, 2);
        Pipe3.setRotationPoint(-1F, 18F, 4F);
        Pipe3.setTextureSize(64, 128);
        Pipe3.mirror = true;
        setRotation(Pipe3, 0F, 0F, 0F);
        Pipe4 = new ModelRenderer(this, 56, 12);
        Pipe4.addBox(0F, 0F, 0F, 3, 1, 1);
        Pipe4.setRotationPoint(-5F, 16F, 4F);
        Pipe4.setTextureSize(64, 128);
        Pipe4.mirror = true;
        setRotation(Pipe4, 0F, 0F, 0F);
        Lava1 = new ModelRenderer(this, 48, 16);
        Lava1.addBox(0F, 0F, 0F, 4, 1, 4);
        Lava1.setRotationPoint(-2F, 22F, -6F);
        Lava1.setTextureSize(64, 128);
        Lava1.mirror = true;
        setRotation(Lava1, 0F, 0F, 0F);
        LavaTexture = new ModelRenderer(this, 48, 21);
        LavaTexture.addBox(0F, 0F, 0F, 4, 1, 4);
        LavaTexture.setRotationPoint(-2F, 21F, -6F);
        LavaTexture.setTextureSize(64, 128);
        LavaTexture.mirror = true;
        setRotation(LavaTexture, 0F, 0F, 0F);
        Lava2 = new ModelRenderer(this, 54, 26);
        Lava2.addBox(0F, 0F, 0F, 4, 2, 1);
        Lava2.setRotationPoint(-2F, 20F, -2F);
        Lava2.setTextureSize(64, 128);
        Lava2.mirror = true;
        setRotation(Lava2, 0F, 0F, 0F);
        Lava3 = new ModelRenderer(this, 54, 29);
        Lava3.addBox(0F, 0F, 0F, 1, 2, 4);
        Lava3.setRotationPoint(-3F, 20F, -6F);
        Lava3.setTextureSize(64, 128);
        Lava3.mirror = true;
        setRotation(Lava3, 0F, 0F, 0F);
        Lava4 = new ModelRenderer(this, 44, 26);
        Lava4.addBox(0F, 0F, 0F, 4, 2, 1);
        Lava4.setRotationPoint(-2F, 20F, -7F);
        Lava4.setTextureSize(64, 128);
        Lava4.mirror = true;
        setRotation(Lava4, 0F, 0F, 0F);
        Lava5 = new ModelRenderer(this, 44, 29);
        Lava5.addBox(0F, 0F, 0F, 1, 2, 4);
        Lava5.setRotationPoint(2F, 20F, -6F);
        Lava5.setTextureSize(64, 128);
        Lava5.mirror = true;
        setRotation(Lava5, 0F, 0F, 0F);
        Lava6 = new ModelRenderer(this, 60, 35);
        Lava6.addBox(0F, 0F, 0F, 1, 3, 1);
        Lava6.setRotationPoint(-3F, 18F, -2F);
        Lava6.setTextureSize(64, 128);
        Lava6.mirror = true;
        setRotation(Lava6, 0F, 0F, 0F);
        Lava7 = new ModelRenderer(this, 56, 35);
        Lava7.addBox(0F, 0F, 0F, 1, 3, 1);
        Lava7.setRotationPoint(-3F, 18F, -7F);
        Lava7.setTextureSize(64, 128);
        Lava7.mirror = true;
        setRotation(Lava7, 0F, 0F, 0F);
        Lava8 = new ModelRenderer(this, 52, 35);
        Lava8.addBox(0F, 0F, 0F, 1, 3, 1);
        Lava8.setRotationPoint(2F, 18F, -7F);
        Lava8.setTextureSize(64, 128);
        Lava8.mirror = true;
        setRotation(Lava8, 0F, 0F, 0F);
        Lava9 = new ModelRenderer(this, 48, 35);
        Lava9.addBox(0F, 0F, 0F, 1, 3, 1);
        Lava9.setRotationPoint(2F, 18F, -2F);
        Lava9.setTextureSize(64, 128);
        Lava9.mirror = true;
        setRotation(Lava9, 0F, 0F, 0F);
        Fat1 = new ModelRenderer(this, 0, 12);
        Fat1.addBox(0F, 0F, 0F, 6, 1, 6);
        Fat1.setRotationPoint(-3F, 17F, -7F);
        Fat1.setTextureSize(64, 128);
        Fat1.mirror = true;
        setRotation(Fat1, 0F, 0F, 0F);
        Fat2 = new ModelRenderer(this, 0, 19);
        Fat2.addBox(0F, 0F, 0F, 1, 4, 6);
        Fat2.setRotationPoint(-4F, 13F, -7F);
        Fat2.setTextureSize(64, 128);
        Fat2.mirror = true;
        setRotation(Fat2, 0F, 0F, 0F);
        Fat3 = new ModelRenderer(this, 14, 19);
        Fat3.addBox(0F, 0F, 0F, 6, 4, 1);
        Fat3.setRotationPoint(-3F, 13F, -1F);
        Fat3.setTextureSize(64, 128);
        Fat3.mirror = true;
        setRotation(Fat3, 0F, 0F, 0F);
        Fat4 = new ModelRenderer(this, 14, 24);
        Fat4.addBox(0F, 0F, 0F, 1, 4, 6);
        Fat4.setRotationPoint(3F, 13F, -7F);
        Fat4.setTextureSize(64, 128);
        Fat4.mirror = true;
        setRotation(Fat4, 0F, 0F, 0F);
        Fat5 = new ModelRenderer(this, 0, 29);
        Fat5.addBox(0F, 0F, 0F, 6, 4, 1);
        Fat5.setRotationPoint(-3F, 13F, -8F);
        Fat5.setTextureSize(64, 128);
        Fat5.mirror = true;
        setRotation(Fat5, 0F, 0F, 0F);
        Fat6 = new ModelRenderer(this, 0, 34);
        Fat6.addBox(0F, 0F, 0F, 6, 1, 6);
        Fat6.setRotationPoint(-3F, 14F, -7F);
        Fat6.setTextureSize(64, 128);
        Fat6.mirror = true;
        setRotation(Fat6, 0F, 0F, 0F);
        Pipe5 = new ModelRenderer(this, 26, 0);
        Pipe5.addBox(0F, 0F, 0F, 1, 1, 8);
        Pipe5.setRotationPoint(-6F, 16F, -3F);
        Pipe5.setTextureSize(64, 128);
        Pipe5.mirror = true;
        setRotation(Pipe5, 0F, 0F, 0F);
        Pipe6 = new ModelRenderer(this, 22, 0);
        Pipe6.addBox(0F, 0F, 0F, 1, 2, 1);
        Pipe6.setRotationPoint(-4F, 15F, -3F);
        Pipe6.setTextureSize(64, 128);
        Pipe6.mirror = true;
        setRotation(Pipe6, 0F, 0F, 1.003822F);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z) {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }
}
